amazon.sp-api.endpoint=https://sellingpartnerapi-eu.amazon.com
amazon.sp-api.region=eu-west-1
amazon.sp-api.marketplace-id=A21TJRUUN4KGV
amazon.sp-api.lwa-client-id=${LWA_CLIENT_ID}
amazon.sp-api.lwa-client-secret=${LWA_CLIENT_SECRET_KEY}
amazon.sp-api.lwa-refresh-token=${LWA_CLIENT_REFRESH_TOKEN}
amazon.sp-api.aws-access-key-id=${AWS_IAM_ACCESS_KEY:}
amazon.sp-api.aws-secret-access-key=${AWS_IAM_SECRET_KEY:}
